# Gateway-specific configuration
gateway:
  timeout: 30s
  
# Resilience4j circuit breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      user-service-cb:
        baseConfig: default
      pet-service-cb:
        baseConfig: default
      appointment-service-cb:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
    instances:
      user-service:
        baseConfig: default
      pet-service:
        baseConfig: default
      appointment-service:
        baseConfig: default

# Logging configuration for reactive components
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG