server:
  port: 8080

spring:
  application:
    name: petify-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      namespace: 8fa7b34f-48a7-4738-92df-932068cfef44
      username: nacos
      password: nacos
      discovery:
        enabled: true
        server-addr: localhost:8848
        namespace: 8fa7b34f-48a7-4738-92df-932068cfef44
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: 8fa7b34f-48a7-4738-92df-932068cfef44
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:petify-gateway-dev.yml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:common-config.yml?group=DEFAULT_GROUP&refresh=true
  data:
    redis:
      host: localhost
      port: 6379